# Data for the three example templates. Each deck is a list of slide dicts.
FEATURES_CORE=[("Return & revise","Nothing is written once. The philosophy statement, goals, and key reflections get a new dated version every cycle — and the old versions stay visible so growth is something you can point to."),
 ("Reflection tied to artifacts","Every reflection links to a specific artifact and quotes or points at a specific place in it. Claims without evidence don't go in."),
 ("Feedback that gets a response","Mentor, cooperating teacher, and peer feedback is logged — and each entry gets a short reply from the student: what changed, or why it didn't."),
 ("Connection across contexts","Prompts ask how this is like, and not like, what came before: another course, a placement, the student's own schooling. That is where transfer happens.")]

CYCLE=[("Process","Describe the work. What surprised or challenged you? What would you do differently, and why? What tools and resources did you use, and how did they help or hinder?"),
 ("Outcomes","How did this artifact help you learn X? Point to the place in it where you demonstrate your ability to do Y."),
 ("Integration","How does this connect to earlier courses, placements, or your own schooling? How does it prepare you for what you hope to do next?"),
 ("Development","How have you grown as a mathematics teacher since the last version? Point to iterations to show it.")]
CYCLE_NOTE=("What the mentor does with it","Reflection that nobody responds to stops happening. Each reflection gets a short reply from the faculty mentor within two weeks — one question, one observation — and the student answers it. The exchange stays on the page.")

ARTIFACT_SECTIONS=[("Artifact","Embedded PDF or Doc. Standards, objectives, anticipated responses."),
 ("Context","Course, placement, grade band, what came just before and after."),
 ("Reflection","Process · Outcomes · Integration · Development — with links to specific parts of the artifact."),
 ("Feedback & reply","Instructor / mentor comment, dated. Student reply, dated."),
 ("Connections","Links to the earlier artifact this builds on, and the philosophy version it informs."),
 ("Next step","One sentence: what this artifact says you should try next.")]

# ------------------------------------------------------------------ 1. Four-Year Build
FOUR_YEAR=dict(
 slug="four-year-build", name="The Four-Year Build",
 tagline="A student who starts in Year 1 and builds the portfolio in step with the whole program.",
 who="First-year math education majors",
 slides=[
  dict(type="title", eyebrow="Mathematics Education · Miami University", head="Show your work.", head2="All four years of it.",
       lede="A student template for the Math Ed ePortfolio: what you add each year, and the habits that turn a folder of files into ongoing learning."),
  dict(type="features", eyebrow="What makes it a learning portfolio", head="A repository stores work. A learning portfolio returns to it.",
       sub="Four features separate an ePortfolio that supports ongoing learning from a website with files on it. Every year of this template is built around them.", items=FEATURES_CORE),
  dict(type="table", eyebrow="MILE alignment", head="Every MILE requirement is met by a math ed artifact",
       sub="MILE asks for About Me, one artifact + reflection from Advanced Writing and from each of three Applied Skills Courses, one from Capstone, and a concluding reflection — all in the Google Site shell from UNV 101, submitted to MILO in Capstone. The math ed portfolio supplies each one.",
       cols=["When","Math ed artifact that fills it","Reflection prompt"],
       rows=[("About Me",["Year 1 · UNV 101","Baseline letter: who you are, who you want to become as a math teacher","Development"]),
             ("ASC · Quantitative reasoning",["Year 1–2 · a math course designated ASC","One piece of your own mathematics, with what was hard","Process · Outcomes"]),
             ("ASC · Oral communication or Teamwork",["Year 2 · methods or ed course designated ASC","First lesson plan (taught or presented) or a lesson-study team plan","Outcomes · Integration"]),
             ("ASC · Problem-solving, Digital fluency, or Civic/ethical",["Year 3 · a course designated ASC","Student-work analysis, an assessment you designed, or a placement equity reflection","Integration"]),
             ("Advanced Writing",["Year 3","Teaching philosophy v3 — the version with every claim linked to an artifact","Development"]),
             ("Capstone artifact",["Year 4 · student teaching / capstone","Classroom video with time-stamped commentary","Outcomes"]),
             ("Concluding reflection",["Year 4 · Capstone","Integrative reflection across all four years; link submitted via MILO form for graduation credit","Integration · Development"])]),
  dict(type="arc", eyebrow="The four-year arc", head="Built in step with the program, not on top of it",
       sub="Two to three artifacts a year. The MILE portfolio shell you create in UNV 101 is the same Google Site; the math ed pages are added alongside it.",
       stages=[("Year 1","Begin the record","Site shell · baseline letter · philosophy v1 · one piece of your own mathematics"),
               ("Year 2","First classroom evidence","Observation notes · first lesson plan · philosophy v2 · goal check-in"),
               ("Year 3","Teach and analyze","Second lesson plan · student-work analysis · assessment you designed · feedback log"),
               ("Year 4","Student teaching & capstone","Classroom video with commentary · philosophy v4 · concluding reflection · MILE submission")],
       recurring=("Every year:","reread last year's letter to your future self · write the next one · new dated philosophy version · goal check-in with your mentor · reply to every piece of logged feedback")),
  dict(type="stage", eyebrow="Year 1 of 4", head="Begin the record", sub="Most of Year 1 is setting a baseline you will come back to. It feels small now; it is the most-referenced material in the whole portfolio.",
       adds=[("Portfolio shell (MILE)","Create your Google Site in UNV 101 — this is the MILE shell. Write the About Me page and add a Math Ed section with placeholder pages for each year."),
             ("Letter to your future self","Who are you, and who do you want to become as a math teacher? What are you worried about? What do you want to learn here?"),
             ("Teaching philosophy v1","One page. It will be wrong in interesting ways, which is the point of keeping it."),
             ("One piece of your own mathematics (MILE · ASC)","A proof or exploration from a first-year course, with a note on what was hard. If the course is a Quantitative Reasoning ASC, this is your MILE artifact for it.")],
       learn=[("Dated versions","Name files and pages with the semester (philosophy-F26). Never overwrite; add."),
              ("Goals you can check","Three concrete goals at the end of the letter. Year 2 opens by grading them."),
              ("A first mentor conversation","Meet your faculty mentor; they get share access to the site — and a promise you'll remove them when you graduate."),
              ("Muddiest point","One sentence: what about teaching math is least clear to you right now?")],
       prompt="What do you already believe about how people learn mathematics — and where did that belief come from?"),
  dict(type="stage", eyebrow="Year 2 of 4", head="First classroom evidence", sub="Early field experience and the first methods course produce the first artifacts from real classrooms. Year 2 is where the connection prompts start doing work.",
       adds=[("Observation notes","From early field experience: what you saw, and one moment you'd have handled differently."),
             ("First lesson plan (MILE · ASC)","From a methods course, with standards alignment and anticipated student responses. If the course is an Oral Communication or Teamwork ASC, submit it with its reflection as the MILE artifact."),
             ("Teaching philosophy v2","Rewritten, not edited. Then a short note: what changed since v1, and what caused it."),
             ("Goal check-in","Reread the Year 1 letter. Score each goal. Write the Year 2 letter.")],
       learn=[("Like / not like","For the lesson plan: how is planning a lesson like, and not like, solving a problem set? Like, and not like, being a student in that lesson?"),
              ("Answer the muddiest point","Return to last year's question. Is it clearer? What made it clearer?"),
              ("Feedback log begins","Methods instructor feedback on the lesson plan goes in — with your reply: what you'd change and why."),
              ("Peer read","Trade portfolios with a classmate; each leaves one comment the other must answer.")],
       prompt="Point to one line in your lesson plan that you would not have written a year ago. What do you know now?"),
  dict(type="stage", eyebrow="Year 3 of 4", head="Teach and analyze", sub="Placements give you student thinking to work with. Year 3 shifts the portfolio from what you planned to what students actually did.",
       adds=[("Second lesson plan","Different grade band or strand than the first — say, middle-school proportional reasoning after a high-school proof lesson."),
             ("Analysis of student work","Real (anonymized) responses to a task you gave, sorted by strategy and misconception, with what you'd do next."),
             ("Assessment you designed","A quiz, task, or rubric, plus results and what they told you."),
             ("Teaching philosophy v3 (MILE · Advanced Writing)","Now with evidence: each claim links to an artifact. This is the Advanced Writing artifact for MILE, reflection included.")],
       learn=[("Lesson wrapper","After teaching: how did you prepare, where did students struggle, what will you do differently next time? Modeled on exam wrappers."),
              ("Compare plan to plan","Set the Year 2 and Year 3 lesson plans side by side. Name three differences and what they show."),
              ("Feedback with response","Cooperating teacher and supervisor observations are logged; each gets a reply within a week."),
              ("Regulatory checklist","Before a lesson: what is the task, my goal, my plan? After: did it work, what didn't, what next?")],
       prompt="Find a student response that surprised you. What did the student understand that your plan didn't anticipate?"),
  dict(type="stage", eyebrow="Year 4 of 4", head="Student teaching & capstone", sub="The last year turns the record into an argument. The capstone reflection is the MILE requirement; the portfolio presentation is the program's.",
       adds=[("Classroom video with commentary (MILE · Capstone)","10–15 minutes of you teaching, with time-stamped notes on the questions you asked and the decisions you made. The Capstone artifact for MILE."),
             ("Teaching philosophy v4","Final version, presented beside v1. The distance between them is the evidence."),
             ("Growth record","Every logged piece of feedback with its response, and what you did about it."),
             ("Concluding reflection (MILE)","The MILE concluding reflection on the whole experience, plus a program reflection that walks a reader through the math ed pages. Submit the site link through MILO's form for graduation credit.")],
       learn=[("Integration reflection","Referencing specific artifacts across all four years: what can you do now that you couldn't? How does this prepare you for your first classroom?"),
              ("Reread every letter","Four letters to your future self, in order. Write the fifth: to yourself at the end of your first year teaching."),
              ("Portfolio presentation","Present to faculty and peers. Then reply to their feedback in the growth record — the last entry."),
              ("Hand-off","Submit the link via the MILO form in Capstone. Remove instructors' access — MILO recommends sharing, not publishing. The site is yours for the job search and beyond.")],
       prompt="Choose one artifact from each year. Together, what story do they tell about how you learned to teach mathematics?"),
  dict(type="cycle", eyebrow="The reflection cycle", head="Every artifact gets a reflection — and the reflection points at the artifact",
       sub="Four prompt families, drawn from the Miami ePortfolios Working Group. Use one or more per artifact; require a link or a quotation from the artifact in every answer.", items=CYCLE, note=CYCLE_NOTE),
  dict(type="table", eyebrow="Features that recur every year", head="The same five moves, four times",
       sub="Ongoing learning comes from repetition with variation. These are the pages a student returns to each year; the grid shows how each one deepens.",
       cols=["Year 1","Year 2","Year 3","Year 4"],
       rows=[("Letter to future self",["Write it: who you are, who you want to become","Reread · score goals · write the next","Reread · score · write the next","Reread all four · write the fifth, to your first-year-teacher self"]),
             ("Teaching philosophy",["v1 — beliefs","v2 — rewritten, with a note on what changed","v3 — each claim links to an artifact","v4 — shown beside v1"]),
             ("Goal check-in",["Set three goals","Grade them; set new ones","Grade; set goals for placement","Grade; set goals for year one of teaching"]),
             ("Feedback log",["Mentor conversation noted","Methods instructor feedback + reply","Cooperating teacher & supervisor + replies","Presentation feedback + final reply"]),
             ("Muddiest point",["One sentence","Answer it; ask the next","Answer; ask","Answer; ask the one you'll carry into teaching"])]),
  dict(type="template", eyebrow="Artifact page template", head="One page, the same shape every time",
       sub="Each artifact in the Google Site follows this layout, so a reader — or the student in Year 4 — can find the reflection and the feedback without hunting.",
       example=("Lesson Plan · Proportional Reasoning, Grade 7","F27 · Methods I"), sections=ARTIFACT_SECTIONS,
       map_title="Site map (Google Sites)",
       map=[("About Me","MILE"),("MILE Portfolio","MILE"),("   Advanced Writing · ASC ×3 · Capstone","MILE"),("Math Ed Portfolio",""),("   Letters & goals",""),("   Teaching philosophy (v1–v4)",""),("   Year 1 · Year 2 · Year 3 · Year 4",""),("   Feedback log",""),("   Growth record",""),("Concluding reflection","MILE")]),
  dict(type="todo", eyebrow="Using this template", head="What the program needs to build, in order of urgency",
       sub="Start with the smallest piece inside your own locus of control. Everything below can be piloted in one methods section before it's a program requirement.",
       items=[("Artifact page template & instructions","One Google Sites page students copy. Include the six section headings and the reflection prompt families."),
              ("Year 1 letter & philosophy prompts","Baseline reflections assigned in UNV 101 or the first math ed course. These must exist before anything else can be revisited."),
              ("Reflection rubric","Shared by all mentors. Two criteria carry most of the weight: is the claim tied to a specific place in the artifact, and does it connect to prior work?"),
              ("Feedback-reply norm","A two-week reply window for mentors, and a one-week reply window for students. Written down, so it happens."),
              ("Year 4 presentation format","Twenty minutes, four artifacts, one per year. Announce it in Year 1 so students select with it in mind."),
              ("ASC designations","Ask which math and education courses will be designated Applied Skills Courses, so the artifact map above matches real course numbers. MILO's reflection-prompt bank and Howe Center workshops cover the rest.")],
       sources="Sources: Miami ePortfolios Working Group, F'26 (Wardle, Olejnik, Boddy, Bapst) · Perkins & Salomon on transfer · Schraw (1998) regulatory checklists · Lovett (2016) exam wrappers · Tanner (2012)"),
 ])

# ------------------------------------------------------------------ 2. The Late Start
LATE_START=dict(
 slug="late-start", name="The Late Start",
 tagline="A transfer student or late-declared major who joins in junior year and builds Years 1–2 backward in one semester.",
 who="Transfer students and juniors declaring math education",
 slides=[
  dict(type="title", eyebrow="Mathematics Education · Miami University", head="Start where you are.", head2="Build backward, then forward.",
       lede="A template for students who join the program in Year 3. One semester reconstructs the baseline from work you already have; the last three semesters run the full cycle."),
  dict(type="features", eyebrow="Principles for a late start", head="Reconstruct honestly. Then run the same cycle as everyone else.",
       sub="The four learning features don't change. What changes is that the first versions are written looking back rather than looking forward.",
       items=[("Reconstruct, don't fabricate","Your Year 1 baseline is a retrospective: who you were when you arrived at college, written now, with the date. Old work from other courses or institutions counts as artifacts."),
              ("Retrospective reflection is still reflection","Prompts ask what you thought then and what you think now, so the first entry already contains a change — the thing the portfolio is designed to show."),
              ("Compressed cycle, same moves","Letters, philosophy versions, goal check-ins, and feedback replies happen each semester instead of each year."),
              ("Same site, same pages","Your MILE shell and Math Ed pages match every other student's, so mentors and the Year 4 presentation work the same way.")]),
  dict(type="table", eyebrow="MILE alignment", head="MILE requirements, compressed to four semesters",
       sub="A late-start student still owes MILE the same pieces: About Me, Advanced Writing, three ASC artifacts, Capstone, and a concluding reflection. Check with MILO on what transfer credit already satisfies; everything else maps below.",
       cols=["When","Math ed artifact that fills it","Note"],
       rows=[("About Me",["Junior fall","Retrospective letter: then and now","Replaces the UNV 101 baseline"]),
             ("ASC · Quantitative reasoning",["Junior fall","Piece of your own mathematics from prior coursework, with retrospective reflection","Confirm with MILO if transferred"]),
             ("ASC · Oral communication or Teamwork",["Junior fall / spring","First lesson plan, taught or presented","From the first methods course"]),
             ("ASC · Problem-solving or other",["Junior spring","Student-work analysis or assessment you designed","From placement"]),
             ("Advanced Writing",["Junior spring / senior fall","Teaching philosophy v3, every claim linked","Whichever semester the course falls"]),
             ("Capstone artifact",["Senior spring","Classroom video with commentary","Student teaching"]),
             ("Concluding reflection",["Senior spring · Capstone","Integrative reflection; link submitted via MILO form","Graduation credit"])]),
  dict(type="arc", eyebrow="The arc", head="One semester back, three semesters forward",
       sub="Junior fall does the reconstruction alongside the first methods course. From junior spring on, the template matches the Four-Year Build.",
       stages=[("Junior fall","Reconstruct","Site shell · retrospective letter · philosophy v1 from old work · two artifacts pulled from prior coursework with retrospective reflections · first lesson plan"),
               ("Junior spring","Teach and analyze","Second lesson plan · student-work analysis · assessment you designed · philosophy v2 · feedback log"),
               ("Senior fall","Placement depth","Lesson wrapper · compare plan to plan · philosophy v3 with evidence · goal check-in"),
               ("Senior spring","Student teaching & capstone","Classroom video with commentary · philosophy v4 beside v1 · concluding reflection · MILE submission")],
       recurring=("Every semester:","reread the last letter · write the next · new dated philosophy version · goal check-in with your mentor · reply to every piece of logged feedback")),
  dict(type="stage", eyebrow="Junior fall", head="Reconstruct the baseline", sub="You have more to work with than you think: transcripts, old assignments, tutoring or coaching experience, your own schooling. The job this semester is to turn that into a dated starting point.",
       adds=[("Portfolio shell (MILE)","Create the Google Site — or use the MILE shell from UNV 101 or its equivalent if you already have one. Write About Me; add the Math Ed section with pages for each semester."),
             ("Retrospective letter","Two parts, both dated now: who you were when you started college and what you believed about teaching; who you are today and who you want to become."),
             ("Teaching philosophy v1","Written from your best memory of what you believed two years ago. Keep it honest; it is supposed to look dated."),
             ("Two artifacts from prior work","A piece of your own mathematics (a Quantitative Reasoning ASC artifact if the course qualifies) and anything teaching-adjacent — a tutoring log, a lesson from another program.")],
       learn=[("Then / now prompts","Every retrospective reflection has two columns: what I thought then, what I think now. The gap is the first evidence of growth."),
              ("Dated versions from day one","philosophy-F27-retro, philosophy-S28. Never overwrite."),
              ("Mentor intake conversation","Your mentor reads the retrospective letter and asks one question you answer on the page."),
              ("Muddiest point","One sentence: what about teaching math is least clear to you right now?")],
       prompt="What did you believe about learning mathematics when you started college? Point to something you wrote or did then that shows it."),
  dict(type="stage", eyebrow="Junior spring", head="Teach and analyze", sub="With the baseline in place, the semester runs the Year 3 template: real students, real work, real feedback.",
       adds=[("Second lesson plan","Different grade band or strand than the fall plan."),
             ("Analysis of student work","Anonymized responses to a task you gave, sorted by strategy and misconception, with what you'd do next."),
             ("Assessment you designed","A quiz, task, or rubric, plus results and what they told you."),
             ("Teaching philosophy v2","Rewritten, with a note on what changed since the retrospective v1 — and what caused it.")],
       learn=[("Compare plan to plan","Fall and spring lesson plans side by side. Name three differences and what they show."),
              ("Feedback log with replies","Methods instructor and cooperating teacher feedback, each with a reply within a week."),
              ("Answer the muddiest point","Return to the fall question; ask the next."),
              ("Peer read","Trade portfolios with a classmate who started in Year 1. Each leaves one comment the other must answer.")],
       prompt="Find a student response that surprised you. What did the student understand that your plan didn't anticipate?"),
  dict(type="stage", eyebrow="Senior year", head="Placement depth, then the argument", sub="Senior fall deepens the placement evidence; senior spring turns the record into a presentation, exactly as in the Four-Year Build.",
       adds=[("Lesson wrapper (fall)","After teaching: how you prepared, where students struggled, what you'll do differently."),
             ("Teaching philosophy v3 and v4","v3 with every claim linked to an artifact; v4 presented beside the retrospective v1."),
             ("Classroom video with commentary (spring)","10–15 minutes with time-stamped notes on your questions and decisions."),
             ("Growth record & concluding reflection (MILE)","Every logged piece of feedback with its response; the MILE concluding reflection plus a program reflection. Submit the link via MILO's form in Capstone.")],
       learn=[("Integration reflection","Referencing artifacts from all four semesters — including the reconstructed ones — what can you do now that you couldn't?"),
              ("Reread every letter","Retrospective, junior spring, senior fall. Write the last: to yourself at the end of your first year teaching."),
              ("Portfolio presentation","Present to faculty and peers; reply to their feedback as the final growth-record entry."),
              ("Hand-off","Submit the MILE link to MILO. Remove instructors' access. Keep the site.")],
       prompt="Your retrospective letter guessed who you would become. Where was it right, where was it wrong, and what does the portfolio show about why?"),
  dict(type="table", eyebrow="Features that recur each semester", head="The same five moves, four times — one semester apart",
       sub="Compressed from yearly to per-semester so that a late-start student still gets four iterations of every recurring feature.",
       cols=["Junior fall","Junior spring","Senior fall","Senior spring"],
       rows=[("Letter",["Retrospective: then and now","Reread · score goals · write the next","Reread · score · write the next","Reread all · write the one to your first-year-teacher self"]),
             ("Teaching philosophy",["v1 — retrospective","v2 — rewritten, with what changed","v3 — each claim links to an artifact","v4 — beside v1"]),
             ("Goal check-in",["Set three goals","Grade; set new ones","Grade; set goals for student teaching","Grade; set goals for year one"]),
             ("Feedback log",["Mentor intake question + reply","Instructor & cooperating teacher + replies","Supervisor + replies","Presentation feedback + final reply"]),
             ("Muddiest point",["One sentence","Answer; ask the next","Answer; ask","Answer; ask the one you'll carry into teaching"])]),
  dict(type="todo", eyebrow="Using this template", head="What the program needs for late-start students",
       sub="Most of it is shared with the Four-Year Build. Three pieces are specific to reconstruction.",
       items=[("Retrospective letter prompt","Two-part, then/now. This is the one document a late-start student cannot borrow from the standard template."),
              ("Prior-work intake checklist","What counts as an artifact from another institution or a non-education course, how to reflect on it retrospectively, and which MILE requirements MILO counts as satisfied by transfer credit."),
              ("Mentor intake conversation guide","One meeting, one question logged on the page. Sets the feedback-reply norm from the first week."),
              ("Semester-cadence calendar","The same five recurring features, mapped to four semesters instead of four years."),
              ("Shared everything else","Artifact page template, reflection rubric, and Year 4 presentation format are identical to the Four-Year Build.")],
       sources="Sources: Miami ePortfolios Working Group, F'26 · Perkins & Salomon on transfer · Schraw (1998) · Tanner (2012)"),
 ])

# ------------------------------------------------------------------ 3. The Course Pilot
COURSE_PILOT=dict(
 slug="course-pilot", name="The Course Pilot",
 tagline="A one-semester methods-course portfolio in a Google Doc with tabs — the same learning features, run in fifteen weeks, inside one instructor's control.",
 who="Faculty piloting portfolios this semester; students in a single methods course",
 slides=[
  dict(type="title", eyebrow="Mathematics Education · Miami University", head="One course.", head2="Fifteen weeks. Every feature.",
       lede="A template for piloting the Math Ed portfolio inside a single methods course, using a Google Doc with tabs. Small enough to run this semester; shaped so it drops into the four-year Google Site later."),
  dict(type="features", eyebrow="Principles for a pilot", head="Same features, shorter loop",
       sub="The working group's advice: start with the smallest manageable piece inside your locus of control. This is that piece.",
       items=[("Google Doc with tabs, not a site","One shared Doc per student: About & goals · Artifact 1 · Artifact 2 · Feedback log · Final reflection. No platform setup, instant instructor access."),
              ("Two artifacts, three reflections","Two full artifacts with reflections, plus a compare-and-contrast reflection between them. That is enough to show change inside one semester."),
              ("Feedback inside the Doc","Instructor comments live in the margin; students reply in the log tab within a week. The reply, not the comment, is graded."),
              ("Built to migrate","Tab headings match the Year 2 pages of the four-year Google Site. When the program adopts the full portfolio, students copy tabs into pages.")]),
  dict(type="table", eyebrow="MILE alignment", head="The pilot is the course's MILE obligation, done well",
       sub="MILE asks every Advanced Writing and ASC instructor to have students submit one artifact and a reflection to their portfolio shell. If the methods course carries an ASC designation, the pilot's Artifact 1 is that submission — and the Doc gives students more than the minimum.",
       cols=["What the pilot produces","Where it goes"],
       rows=[("One artifact",["Artifact 1 — lesson plan (Oral Communication or Teamwork ASC) or Artifact 2 — student-work analysis (Problem-solving ASC)","Copied from the Doc tab into the student's Google Site shell"]),
             ("One reflection",["Reflection using MILO's prompt families — Process, Outcomes, Integration, Development — linked to a specific part of the artifact","Same page as the artifact"]),
             ("Portfolio shell exists",["Week 1 check: does the student have a MILE shell from UNV 101? If not, create it alongside the Doc","Google Sites"]),
             ("Not required, but the point",["Baseline letter, philosophy v1 → v2, feedback log with replies, compare-and-contrast, final integrative reflection","Stays in the Doc; migrates to Math Ed pages if the program adopts the four-year build"])]),
  dict(type="arc", eyebrow="The semester", head="Four phases, one Doc",
       sub="Baseline in the first two weeks, an artifact cycle in each of the middle two phases, and a final reflection that reads the whole Doc back.",
       stages=[("Weeks 1–2","Baseline","Copy the Doc · letter to end-of-semester self · philosophy v1 · three goals · muddiest point"),
               ("Weeks 3–7","Artifact 1","Lesson plan with reflection · instructor feedback · reply · peer read"),
               ("Weeks 8–12","Artifact 2","Student-work analysis or assessment · reflection · compare with Artifact 1 · feedback and reply"),
               ("Weeks 13–15","Read it back","Reread the letter · grade the goals · philosophy v2 beside v1 · final integrative reflection")],
       recurring=("Every phase:","one reflection tied to a specific artifact · one instructor comment answered in the log · goals revisited")),
  dict(type="stage", eyebrow="Weeks 1–2", head="Baseline", sub="Everything later in the semester refers back to these two weeks. It takes one class session and one homework.",
       adds=[("Copy the Doc template","Five tabs, headings already in place. Share with the instructor as an editor. Confirm you have a MILE Google Site shell from UNV 101; create one if not."),
             ("Letter to your end-of-semester self","Who are you as a math teacher right now? What do you want to be able to do by December? What worries you?"),
             ("Teaching philosophy v1","Half a page. Kept exactly as written."),
             ("Three goals and a muddiest point","Concrete enough to grade in Week 14.")],
       learn=[("Dated, never overwritten","Each version is a new heading with the week number."),
              ("Instructor reads and asks one question","Logged in the Feedback tab; the student's reply is the first graded entry."),
              ("Cue prior knowledge","What experiences, identities, and strengths do you bring to teaching math? Where might they need repurposing?"),
              ("Set the reply norm","Instructor comments within a week; student replies within a week. Announced in the syllabus.")],
       prompt="What do you already believe about how people learn mathematics — and where did that belief come from?"),
  dict(type="stage", eyebrow="Weeks 3–12", head="Two artifact cycles", sub="Each cycle: make the artifact, reflect on it with a link to a specific part, get feedback, reply. The second cycle adds a comparison with the first.",
       adds=[("Artifact 1 · lesson plan (MILE artifact)","Standards alignment and anticipated student responses. Reflection: Process and Outcomes prompts. Copied to the Google Site shell as the course's MILE submission."),
             ("Artifact 2 · student-work analysis or assessment","Anonymized responses sorted by strategy, or an assessment with results. Reflection: Outcomes and Integration prompts."),
             ("Compare-and-contrast reflection","Artifact 2 beside Artifact 1: three differences and what they show about what you've learned."),
             ("Feedback log entries","One instructor comment per artifact, each with a dated reply.")],
       learn=[("Like / not like","How is analyzing student work like, and not like, planning the lesson? Like, and not like, being a student?"),
              ("Peer read","Trade Docs at Week 6; leave one comment the other must answer in their log."),
              ("Lesson wrapper","If Artifact 1 is taught in a placement: how did you prepare, where did students struggle, what next?"),
              ("Mid-semester goal check","Week 8: reread the goals. One sentence each on progress.")],
       prompt="Point to one line in Artifact 2 that you could not have written before Artifact 1. What changed?"),
  dict(type="stage", eyebrow="Weeks 13–15", head="Read it back", sub="The final reflection is written with the whole Doc open. It references specific tabs and quotes them.",
       adds=[("Reread the Week 1 letter","Grade each goal. Answer the muddiest point — or explain why it's still muddy."),
             ("Teaching philosophy v2","Rewritten, placed beside v1, with a note on what changed and what caused it."),
             ("Final integrative reflection","Referencing both artifacts, the feedback log, and the letter: what can you do now that you couldn't in Week 1? What transfers to your next course or placement?"),
             ("Letter to next-semester self","Three goals for the next course. This becomes the first entry of the next cycle.")],
       learn=[("Integration prompt","How does this semester's work connect to earlier courses and to your own schooling? How does it prepare you for student teaching?"),
              ("Instructor's closing reply","One paragraph on the growth the instructor sees, with tab references. The last entry in the log."),
              ("Exit permission","The student keeps the Doc; the instructor is removed as editor, by the student, after grades post."),
              ("Migration note","Artifact 1 and its reflection go to the MILE shell now. If the program adopts the four-year Site, copy every tab into the matching Year 2 page.")],
       prompt="Reread your Week 1 letter. Which of your worries turned out to be the right ones? What does the Doc show about how you handled them?"),
  dict(type="template", eyebrow="The Doc template", head="Five tabs, fixed headings",
       sub="Students copy this Doc in Week 1. The artifact tabs follow the same section order as the four-year artifact page, so the pilot migrates without rewriting.",
       example=("Artifact 1 · Lesson Plan","Tab 2 of 5"), sections=ARTIFACT_SECTIONS,
       map_title="Doc tabs",
       map=[("About & goals","WK 1"),("   Letter · philosophy v1 · three goals · muddiest point",""),("Artifact 1","WK 3–7"),("Artifact 2","WK 8–12"),("   includes compare-and-contrast",""),("Feedback log","ALL"),("   instructor comment → student reply, dated",""),("Final reflection","WK 13–15"),("   philosophy v2 beside v1 · integrative reflection · next letter","")]),
  dict(type="todo", eyebrow="Running the pilot", head="Materials to create, in order",
       sub="From the Week 3 working-group homework: instructions, prompts, grading criteria. Three documents get the pilot running; two more make it repeatable.",
       items=[("The Doc template","Five tabs with headings and the reflection prompts already in place. Students copy it in Week 1."),
              ("Reflection prompts by week","Baseline, Artifact 1, Artifact 2, compare-and-contrast, final. Each names the artifact it must link to."),
              ("Grading criteria","Reflections graded on two things: is the claim tied to a specific place in the artifact, and did the student reply to feedback? Not on length."),
              ("Syllabus language","The reply-norm and the permission hand-off, in writing."),
              ("End-of-semester debrief","One page from the instructor: what worked, what to change, whether to propose the four-year version to the program. Bring it to MILO and the Howe Center faculty help sessions.")],
       sources="Sources: Miami ePortfolios Working Group, F'26, Weeks 2–3 (Google Doc with tabs; locus of control) · Lovett (2016) exam wrappers · Schraw (1998)"),
 ])



DECKS=[FOUR_YEAR,LATE_START,COURSE_PILOT]
